### ISSUE TITLE
Android Screensaver return to running app

### ISSUE THREAD

**Issue by nkonidaris** [immichFrame/ImmichFrame#148] opened 2024-10-03 10:34 UTC
### Description

Good day, Team
Firstly I would like to thank all the contributors for such an amazing app and their hard work keeping improvement and features on-going.

I would like to ask for a possible feature or perhaps be point in the direction how to easily achieve the desired result. 

I have an Android Touch Display (Sonoff NSPanel Pro) running Oreo 8.1 with Home Assistant Companion app installed. I am wanting to use ImmichFrame as a screensaver while the touch panel isnt being used. However, when the user touches the screen (or proximity sensor which normally wakes the device from sleep) I would like the already running Home Assistant app to open again. With screensaver off it seems to work fine waking from sleep but when using Immich Frame as screensaver it appears to just open the Immich Frame app when display goes to sleep. 

Any help would be greatly appreciated!

Kind regards
Nicholas 

### Use Case

Allowing users to use the immich frame as a home assistant control panel interface.

### Pre-Submission Checklist

- [X] This is a feature request and not a bug report

- [X] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment] 2024-10-03 12:58
I'm not sure I fully understand. Are you wanting the Home Assistant app running, then after timeout the ImmichFrame screensaver launches, then when you touch the screen to "wake" it ImmichFrame stops and Home Assistant is shown again? This would be a pretty big tear-up as you are correct, the screensaver function essentially just launches the app. Google has been slowly deprecating screensaver functionality in every new version. You can't even set it anymore in newer Google TV without using ADB, so I'm not sure the effort is worth it.

**Comment by nkonidaris** [comment] 2024-10-03 22:59
Hey, @3rob3 
Thanks for your quick response! You are spot on!
I have got it somewhat working using a mod toolkit from seaky ([nspanel_pro_tools_apk](https://github.com/seaky/nspanel_pro_tools_apk)) but it doesnt always work and you have to click the bottom of the screen else you pause the slide show or enter the settings. I might need to do more research into how screensavers work in Android, ideally I would like a touch of the screen and/or proximity sensor to switch to HA app.

Side feature request: This might be a problem due to lack of processing power of device but when the screensaver begins the screen goes completely white while launching the app, to Immich Logo, and finally the photos. This can be quite eye piercing at night, perhaps a setting to make startup background black and skip the immich logo until the photos are ready to display.

Thanks again for all the help!

**Comment by 3rob3** [comment] 2024-10-03 23:36
If your device supports it, enable dark mode. ImmichFrame will follow that setting and show black background. I will keep thinking how to improve screensaver

**Comment by nkonidaris** [comment] 2024-10-04 07:35
Dark mode worked wonders, thanks!

**Comment by 3rob3** [comment] 2024-11-01 11:59
> @3rob3 Will this be fixed with the recent changes?

Yep!

**Comment by 3rob3** [comment] 2024-11-21 14:48
Closing, screensaver works as intended with Webview version of app.

**Closed by 3rob3** 2024-11-21 14:48 UTC
Labels: enhancement
